export const MODEL_UPDATE_PROFILE_REQUEST = 'MODEL_UPDATE_PROFILE_REQUEST';
export const MODEL_UPDATE_PROFILE_SUCCESS = 'MODEL_UPDATE_PROFILE_SUCCESS';
export const MODEL_UPDATE_PROFILE_FAIL = 'MODEL_UPDATE_PROFILE_FAIL';
export const MODEL_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';
