export const MODEL_LIST_REQUEST = 'MODEL_LIST_REQUEST';
export const MODEL_LIST_SUCCESS = 'MODEL_LIST_SUCCESS';
export const MODEL_LIST_FAIL = 'MODEL_LIST_FAIL';

export const MODEL_ALL_REQUEST = 'MODEL_ALL_REQUEST';
export const MODEL_ALL_SUCCESS = 'MODEL_ALL_SUCCESS';
export const MODEL_ALL_FAIL = 'MODEL_ALL_FAIL';
export const MODEL_ALL_RESET = 'MODEL_ALL_RESET';

export const MODEL_DETAILS_REQUEST = 'MODEL_DETAILS_REQUEST';
export const MODEL_DETAILS_SUCCESS = 'MODEL_DETAILS_SUCCESS';
export const MODEL_DETAILS_FAIL = 'MODEL_DETAILS_FAIL';
export const MODEL_DETAILS_RESET = 'MODEL_DETAILS_RESET';

export const MODEL_LOGIN_REQUEST = 'MODEL_LOGIN_REQUEST';
export const MODEL_LOGIN_SUCCESS = 'MODEL_LOGIN_SUCCESS';
export const MODEL_LOGIN_FAIL = 'MODEL_LOGIN_FAIL';
export const MODEL_LOGOUT = 'MODEL_LOGOUT';

export const MODEL_REGISTER_REQUEST = 'MODEL_REGISTER_REQUEST';
export const MODEL_REGISTER_SUCCESS = 'MODEL_REGISTER_SUCCESS';
export const MODEL_REGISTER_FAIL = 'MODEL_REGISTER_FAIL';

export const MODEL_UPDATE_PROFILE_REQUEST = 'MODEL_UPDATE_PROFILE_REQUEST';
export const MODEL_UPDATE_PROFILE_SUCCESS = 'MODEL_UPDATE_PROFILE_SUCCESS';
export const MODEL_UPDATE_PROFILE_FAIL = 'MODEL_UPDATE_PROFILE_FAIL';
export const MODEL_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const MODEL_DELETE_REQUEST = 'MODEL_DELETE_REQUEST';
export const MODEL_DELETE_SUCCESS = 'MODEL_DELETE_SUCCESS';
export const MODEL_DELETE_FAIL = 'MODEL_DELETE_FAIL';

export const MODEL_UPDATE_REQUEST = 'MODEL_UPDATE_REQUEST';
export const MODEL_UPDATE_SUCCESS = 'MODEL_UPDATE_SUCCESS';
export const MODEL_UPDATE_FAIL = 'MODEL_UPDATE_FAIL';
export const MODEL_UPDATE_RESET = 'USER_UPDATE_RESET';

export const MODEL_CREATE_REVIEW_REQUEST = 'MODEL_CREATE_REVIEW_REQUEST';
export const MODEL_CREATE_REVIEW_SUCCESS = 'MODEL_CREATE_REVIEW_SUCCESS';
export const MODEL_CREATE_REVIEW_FAIL = 'MODEL_CREATE_REVIEW_FAIL';
export const MODEL_CREATE_REVIEW_RESET = 'MODEL_CREATE_REVIEW_RESET';
