export const ADMIN_CREATE_PLAN_REQUEST = "ADMIN_CREATE_PLAN_REQUEST";
export const ADMIN_CREATE_PLAN_SUCCESS = "ADMIN_CREATE_PLAN_SUCCESS";
export const ADMIN_CREATE_PLAN_FAIL = "ADMIN_CREATE_PLAN_FAIL";

export const ADMIN_UPDATE_PLAN_REQUEST = "ADMIN_UPDATE_PLAN_REQUEST";
export const ADMIN_UPDATE_PLAN_SUCCESS = "ADMIN_UPDATE_PLAN_SUCCESS";
export const ADMIN_UPDATE_PLAN_FAIL = "ADMIN_UPDATE_PLAN_FAIL";

export const ADMIN_DELETE_PLAN_REQUEST = "ADMIN_DELETE_PLAN_REQUEST";
export const ADMIN_DELETE_PLAN_SUCCESS = "ADMIN_DELETE_PLAN_SUCCESS";
export const ADMIN_DELETE_PLAN_FAIL = "ADMIN_DELETE_PLAN_FAIL";

export const ADMIN_PLAN_DETAILS_REQUEST = "ADMIN_PLAN_DETAILS_REQUEST";
export const ADMIN_PLAN_DETAILS_SUCCESS = "ADMIN_PLAN_DETAILS_SUCCESS";
export const ADMIN_PLAN_DETAILS_FAIL = "ADMIN_PLAN_DETAILS_FAIL";

export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST';
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS';
export const PLAN_LIST_FAIL = 'PLAN_LIST_FAIL';

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";