export const PAYSTACK_KEYS_REQUEST = "PAYSTACK_KEYS_REQUEST";
export const PAYSTACK_KEYS_SUCCESS = "PAYSTACK_KEYS_SUCCESS";
export const PAYSTACK_KEYS_FAIL = "PAYSTACK_KEYS_FAIL";
export const PAYSTACK_KEYS_RESET = "PAYSTACK_KEYS_RESET";