export const ADMIN_CREATE_SUB_REQUEST = "ADMIN_CREATE_SUB_REQUEST";
export const ADMIN_CREATE_SUB_SUCCESS = "ADMIN_CREATE_SUB_SUCCESS";
export const ADMIN_CREATE_SUB_FAIL = "ADMIN_CREATE_SUB_FAIL";

export const ADMIN_ENABLE_SUB_REQUEST = "ADMIN_ENABLE_SUB_REQUEST";
export const ADMIN_ENABLE_SUB_SUCCESS = "ADMIN_ENABLE_SUB_SUCCESS";
export const ADMIN_ENABLE_SUB_FAIL = "ADMIN_ENABLE_SUB_FAIL";

export const ADMIN_DISABLE_SUB_REQUEST = "ADMIN_DISABLE_SUB_REQUEST";
export const ADMIN_DISABLE_SUB_SUCCESS = "ADMIN_DISABLE_SUB_SUCCESS";
export const ADMIN_DISABLE_SUB_FAIL = "ADMIN_DISABLE_SUB_FAIL";

export const SUB_DETAILS_REQUEST = "SUB_DETAILS_REQUEST";
export const SUB_DETAILS_SUCCESS = "SUB_DETAILS_SUCCESS";
export const SUB_DETAILS_FAIL = "SUB_DETAILS_FAIL";

export const SUB_LIST_REQUEST = 'SUB_LIST_REQUEST';
export const SUB_LIST_SUCCESS = 'SUB_LIST_SUCCESS';
export const SUB_LIST_FAIL = 'SUB_LIST_FAIL';