const products = [
  {
    _id: '1',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    number: '08033105490',
  },
  {
    _id: '2',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    number: '08033105490',
  },
  {
    _id: '3',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    number: '08033105490',
  },
  {
    _id: '4',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: false,
    number: '08033105490',
  },
  {
    _id: '5',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    number: '08033105490',
  },
  {
    _id: '6',
    name: 'Anita',
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    description:
      "I am sweet, sexy, naughty and soft. I love my body to be explored till orgasm. Thick, juicy, sexy, and soft body. No jokes. I'm here to take you on aride with my sweet body. My body is so soft. Iam in Lagos call me",
    brand: 'Apple',
    category: 'Electronics',
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: false,
    number: '08033105490',
  },
];

export default products;
