const models = [
  {
    _id: '1',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '2',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '3',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '4',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '5',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '6',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
  {
    _id: '7',
    name: 'jojo',
    email: 'jojo@email.com',
    password: 'password',
    about:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam nulla in, amet odit magni a error sit maiores officia fugit',
    DOB: '03 - 03 - 1998',
    country: 'Nigeria',
    state: 'Abuja',
    city: 'Gwarinpa',
    states_visited_often: ['Lagos', 'Imo'],
    price: 5000,
    rating: 4.5,
    numReviews: 12,
    isVerified: true,
    images: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    nudeImages: [
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
      '/images/1.jpg',
    ],
    verifiedImage: '/images/1.jpg',
    openToDinnerDates: true,
    minimumCash: '20000',
    privateInfo: {
      phoneNumber1: '0000',
      phoneNumber2: '0000',
      whatsappNumber: '000000',
    },
  },
];

export default models;
